/* eslint-disable */
/**
 * Generated `api` utility.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED.
 *
 * Generated by convex@1.8.0.
 * To regenerate, run `npx convex dev`.
 * @module
 */

import type {
  ApiFromModules,
  FilterApi,
  FunctionReference,
} from "convex/server";
import type * as Notes_mutation from "../Notes/mutation.js";
import type * as Notes_query from "../Notes/query.js";
import type * as Users_functions from "../Users/functions.js";
import type * as Users_mutation from "../Users/mutation.js";
import type * as Users_query from "../Users/query.js";

/**
 * A utility for referencing Convex functions in your app's API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = api.myModule.myFunction;
 * ```
 */
declare const fullApi: ApiFromModules<{
  "Notes/mutation": typeof Notes_mutation;
  "Notes/query": typeof Notes_query;
  "Users/functions": typeof Users_functions;
  "Users/mutation": typeof Users_mutation;
  "Users/query": typeof Users_query;
}>;
export declare const api: FilterApi<
  typeof fullApi,
  FunctionReference<any, "public">
>;
export declare const internal: FilterApi<
  typeof fullApi,
  FunctionReference<any, "internal">
>;
